version: '3.9'
services: 
  postgres-docker-service:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      -  "5432:5432"
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_SOUECE=postgresql://root:secret@postgres-docker-service:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres-docker-service
    entrypoint: [ "/app/wait-forv2.2.3.sh" , "postgres-docker-service:5432" , "--" , "/app/start.sh" ]
    command: [ /app/test_simplebank ]
