// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type CustomerAccount struct {
	ID           int64     `json:"id"`
	CustomerName string    `json:"customer_name"`
	Balance      int64     `json:"balance"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
}

type Entry struct {
	ID         int64     `json:"id"`
	CustomerID int64     `json:"customer_id"`
	Amount     int64     `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transaction struct {
	ID                   int64         `json:"id"`
	FromCustomerAccounts sql.NullInt64 `json:"from_customer_accounts"`
	ToCustomerAccounts   sql.NullInt64 `json:"to_customer_accounts"`
	Amount               int64         `json:"amount"`
	CreatedAt            time.Time     `json:"created_at"`
}
