// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CustomerAccount, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCustomer(ctx context.Context, id int64) error
	GetCustomer(ctx context.Context, id int64) (CustomerAccount, error)
	GetCustomerForUpdate(ctx context.Context, id int64) (CustomerAccount, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListCustomer(ctx context.Context, arg ListCustomerParams) ([]CustomerAccount, error)
	ListCustomerWithOwner(ctx context.Context, arg ListCustomerWithOwnerParams) ([]CustomerAccount, error)
	ListEntries(ctx context.Context, id int64) (Entry, error)
	ListEntriesByCustomerID(ctx context.Context, customerID int64) ([]Entry, error)
	ListTransaction(ctx context.Context, id int64) (Transaction, error)
	ListTransactionWithAmount(ctx context.Context, amount int64) ([]Transaction, error)
	ListTransactionWithFromID(ctx context.Context, fromCustomerAccounts int64) ([]Transaction, error)
	ListTransactionWithToID(ctx context.Context, toCustomerAccounts int64) ([]Transaction, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (CustomerAccount, error)
	UpdateCustomerBalance(ctx context.Context, arg UpdateCustomerBalanceParams) (CustomerAccount, error)
	UpdateCustomerCurrency(ctx context.Context, arg UpdateCustomerCurrencyParams) (CustomerAccount, error)
}

var _ Querier = (*Queries)(nil)
