name: run-unit-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  m-test-golang-unit-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: install go migation cli
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: run migrations file in golang repo
      run: make dbup

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: download Go dependency
      run: go get -u ./...

    - name: Test
      run: make test
